import { precacheAndRoute } from 'workbox-precaching'

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || [])

self.addEventListener('push', function(event) {
  const data = event.data ? event.data.json() : {}
  const title = data.title || '알림'
  const options = {
    body: data.body || '새로운 메시지가 도착했습니다.',
    icon: '/pwa-192x192.png',
    badge: '/mask-icon.svg'
  }

  event.waitUntil(self.registration.showNotification(title, options))
})

self.addEventListener('notificationclick', function(event) {
  event.notification.close()
  event.waitUntil(
    clients.matchAll({ type: 'window' }).then((clientList) => {
      for (const client of clientList) {
        if (client.url === '/' && 'focus' in client) {
          return client.focus()
        }
      }
      if (clients.openWindow) {
        return clients.openWindow('/')
      }
    })
  )
})
